# Problema2


Lea el archivo 'winemag-data-130k-v2.csv' y realice lo siguiente:

- Explore el dataframe según lo visto en clase
- Realice al menos  4 renombre de columna y 3 creación de nuevas columnas según criterio. Deberá crear las columnas que crea conveniente. 
    Ejemplo: Según el país etiquetelos según continente.

- Genere 4 reportes por agrupamiento de datos. Deberá elegir que reportes realizar
    - Ejemplo: Por contienente mostrar los vinos mejor puntuados
    - Ejemplo2: Promedio de precio de vino y cantidad de reviews obtenidos según pais. Ordenado de mejor a peor 


- Al menos uno de estos datos agrupados deberán ser almacenados en excel o csv
   
   Puede revisar esta solución https://stackoverflow.com/questions/25789264/pandas-dataframegroupby-export-to-excel



### Datos 

winemag-data-130k-v2.csv
- https://github.com/gdelgador/ProgramacionPython202401/blob/main/Modulo5/src/winemag-data-130k-v2.csv

País según continente:
- https://gist.githubusercontent.com/kintero/7d1db891401f56256c79/raw/a61f6d0dda82c3f04d2e6e76c3870552ef6cf0c6/paises.csv

In [16]:
#Explorando:
import pandas as pd
df_paises = pd.read_csv("data/winemag-data-130k-v2.csv")
#df_paises.head(5)
df_paises.dtypes

Unnamed: 0                 int64
country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
dtype: object

In [38]:
#renombre y creación de columnas
import pandas as pd
import requests
from io import StringIO

url = "https://gist.githubusercontent.com/kintero/7d1db891401f56256c79/raw/a61f6d0dda82c3f04d2e6e76c3870552ef6cf0c6/paises.csv"
response = requests.get(url)
data = response.content.decode('utf-8')
paises_df = pd.read_csv(StringIO(data))

# Renombrando 
columnas_paises = {
    ' name': 'nombre',
    ' iso2': 'iso2',
    ' iso3': 'iso3',
    ' phone_code': 'phone_code',
    'continente': 'continente'
}
paises_df.rename(columns=columnas_paises, inplace=True)

# Leer el archivo CSV de vinos
df = pd.read_csv('data/winemag-data-130k-v2.csv')

# Renombrando
renames = {
    'country': 'país',
    'description': 'descripción',
    'designation': 'designación',
    'taster_name': 'catador_nombre',
    'title': 'título',
    'variety': 'variedad',
    'winery': 'bodega'
}
df_renamed = df.rename(columns=renames)

# Merge
df_merge = pd.merge(df_renamed, paises_df[['iso2', 'continente']], left_on='país', right_on='iso2', how='left')
df_merge.drop(columns=['iso2'], inplace=True)

# Creación de columnas
import random
df_merge['Población'] = [random.randint(1000000, 10000000) for _ in range(len(df_merge))]
df_merge['Ingresos'] = [random.randint(10000, 50000) for _ in range(len(df_merge))]


df_merge.head(5)

,Unnamed: 0,país,descripción,designación,points,price,province,region_1,region_2,catador_nombre,taster_twitter_handle,título,variedad,bodega,continente,Población,Ingresos
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,NaN,4918573,35864
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,NaN,8570551,10377
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,América,1939059,31444
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,América,3187984,37243
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,América,5726946,21614

In [45]:
#Reporte 1 Mostrar los 2 vinos mejor puntuados de América:

reporte_1 = df_merge[df_merge['continente'].isin(['América'])].groupby('continente').apply(lambda x: x.nlargest(2, 'points')).reset_index(drop=True)
reporte_1.head()

/tmp/ipykernel_10897/2440645581.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reporte_1 = df_merge[df_merge['continente'].isin(['América'])].groupby('continente').apply(lambda x: x.nlargest(2, 'points')).reset_index(drop=True)

,Unnamed: 0,país,descripción,designación,points,price,province,region_1,region_2,catador_nombre,taster_twitter_handle,título,variedad,bodega,continente,Población,Ingresos
0,45798,US,Tasted in a flight of great and famous Napa wi...,NaN,100,200.0,California,Napa Valley,Napa,NaN,NaN,Cardinale 2006 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Cardinale,América,9270317,33726
1,1556,US,The flagship wine from Quilceda Creek offers e...,NaN,99,125.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Quilceda Creek 2008 Cabernet Sauvignon (Columb...,Cabernet Sauvignon,Quilceda Creek,América,7686219,28285

In [46]:
#REPORTE 2 Promedio de precio de vino y cantidad de reviews obtenidos según país. Ordenado de mejor a peor:
reporte_2 = df_merge.groupby('país').agg({'price': 'mean', 'points': 'sum'}).sort_values(by=['price', 'points'], ascending=[False, False]).reset_index()
reporte_2.head(5)

          país      price  points
0  Switzerland  97.000000     351
1      England  51.636364    3285
2      Hungary  50.819672    5455
3       France  41.577949  993050
4      Germany  40.592233   94389

In [47]:
#REPORTE 3 De América  mostrar los 2 países con mayor población:
reporte_3 = df_merge[df_merge['continente'].isin(['América'])].groupby('continente').apply(lambda x: x.nlargest(2, 'Población')).reset_index(drop=True)
reporte_3.head()

/tmp/ipykernel_10897/1833153880.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reporte_3 = df_merge[df_merge['continente'].isin(['América'])].groupby('continente').apply(lambda x: x.nlargest(2, 'Población')).reset_index(drop=True)

,Unnamed: 0,país,descripción,designación,points,price,province,region_1,region_2,catador_nombre,taster_twitter_handle,título,variedad,bodega,continente,Población,Ingresos
0,20771,US,"Heavy and inert, with simple cherry Lifesaver ...",NaN,82,15.0,California,California,California Other,NaN,NaN,Donovan-Parke 2010 Pinot Noir (California),Pinot Noir,Donovan-Parke,América,9999945,13776
1,21441,US,Smoothness and subtlety come with a texture ju...,NaN,88,12.0,California,California,California Other,Jim Gordon,@gordone_cellars,Mirassou 2015 Pinot Grigio (California),Pinot Grigio,Mirassou,América,9999718,43382

In [48]:
#REPORTE 4 De América, mostrar los 2 países con mayor ingresos:
reporte_4 = df_merge[df_merge['continente'].isin(['América'])].groupby('continente').apply(lambda x: x.nlargest(2, 'Ingresos')).reset_index(drop=True)
reporte_4.head()

/tmp/ipykernel_10897/597240646.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  reporte_4 = df_merge[df_merge['continente'].isin(['América'])].groupby('continente').apply(lambda x: x.nlargest(2, 'Ingresos')).reset_index(drop=True)

,Unnamed: 0,país,descripción,designación,points,price,province,region_1,region_2,catador_nombre,taster_twitter_handle,título,variedad,bodega,continente,Población,Ingresos
0,41534,US,"This dessert-style wine is very fruity, quite ...",Black Muscat,88,12.0,California,Amador County,Sierra Foothills,Jim Gordon,@gordone_cellars,Shenandoah Vineyards 2013 Black Muscat Muscat ...,Muscat Hamburg,Shenandoah Vineyards,América,3760041,49999
1,56481,US,Longtime Winemaker Kathy Joseph has crafted a ...,Lollapalooza Fiddlestix,93,80.0,California,Sta. Rita Hills,Central Coast,Matt Kettmann,@mattkettmann,Fiddlehead 2010 Lollapalooza Fiddlestix Pinot ...,Pinot Noir,Fiddlehead,América,5160164,49999

In [49]:
#ALMACENANDO EN EXCEL
with pd.ExcelWriter('reporte_vinos_continente.xlsx') as writer:
    reporte_1.to_excel(writer, sheet_name='Reporte 1', index=False)
    reporte_2.to_excel(writer, sheet_name='Reporte 2', index=False)
    reporte_3.to_excel(writer, sheet_name='Reporte 3', index=False)
    reporte_4.to_excel(writer, sheet_name='Reporte 4', index=False)